### ISSUE TITLE
Change the StringToCSharpIdentifier using UTF-8 Encoding  or Chose by user

### ISSUE THREAD

**Issue by lsysunbow** [rappen/LCG-UDG#103]
Hi @rappen ：
    
 Thank you for your work on this tool， and it is very useful.

And when I use the tool generate the entity optionsets,  in my environment , the default encode charsets is not support the default language,  I found that the default encode charset is 'ISO-8859-8' ,and it's hard code,.

would you like to change the  default encode charset to 'UTF-8', or  change that can be configure by user?

![image](https://github.com/rappen/LCG-UDG/assets/3794589/e1b09770-6298-4ab7-bdf2-f2af5bef1cf4)

**Comment by rappen** [comment]
Thanks - fixed by your PR #104
