### ISSUE TITLE
Include MetaData in UML Diagram Generator to track metadata against an entity to allow for grouping of entities?

### ISSUE THREAD

**Issue by mattritchie** [rappen/LCG-UDG#111]
Hi!
Love your tool!

I'm finding that I'm generating diagrams and then manually sorting them via the plantuml syntax and I'm getting tired of redoing this work.

This is an example

````
package MainEntities{
   entity Contact 
}
package SupportingEntities{
   entity ConsultationRecord
}
````

I have just noticed that the plantuml now contains the xml metadata allowing users to reload the plantuml in the tool. I'm hoping it would be a good place to store this metadata as there is no way that I can see to extend dataverse with this information.

Thanks!

**Comment by rappen** [comment]
Thanks - good idea!
I'll try to implement it, and I hope the result will look something like this:

![image](https://github.com/user-attachments/assets/abe1d74a-4d8c-416e-82c1-abc647cc0589)
