### ISSUE TITLE
As of the newest update the Relationships checkbox causes an error

### ISSUE THREAD

**Issue by ThreeTen22** [rappen/LCG-UDG#32]
I tried selecting all different combinations of entities, including only system entities, only custom entites, a single system entity, and a single custom entity.

As I have global admin I do not think it is a permissions issue.
related error log below:

> System.ArgumentNullException: Value cannot be null.
> Parameter name: source
>    at System.Linq.Enumerable.Where[TSource](IEnumerable`1 source, Func`2 predicate)
>    at Rappen.XTB.LCG.CSharpUtils.GetRelationships(EntityMetadataProxy entitymetadata, List`1 includedentities, Settings settings)
>    at Rappen.XTB.LCG.CSharpUtils.GetClass(List`1 selectedentities, EntityMetadataProxy entitymetadata, EntityMetadataProxy commonentity, Settings settings)
>    at Rappen.XTB.LCG.CSharpUtils.GenerateClasses(List`1 entitiesmetadata, Settings settings, IConstantFileWriter fileWriter)
>    at Rappen.XTB.LCG.LCG.btnGenerate_Click(Object sender, EventArgs e)
>    at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
>    at System.Windows.Forms.ToolStripButton.OnClick(EventArgs e)
>    at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
>    at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
>    at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
>    at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
>    at System.Windows.Forms.Control.WndProc(Message& m)
>    at System.Windows.Forms.ToolStrip.WndProc(Message& m)
>    at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
> 
>

**Comment by rappen** [comment]
Curious to try to understand this, could you paste a screenshot of your configuration, or even better Save Configuration and post that?

**Comment by rappen** [comment]
No feedback, closing. Feel free to reopen if this occurs again.
