### ISSUE TITLE
Attribute Contact.PrimaryKey ("contactid") is mapped as "address1_addressid" 

### ISSUE THREAD

**Issue by maerger** [rappen/LCG-UDG#35]
Here my configuration:
![image](https://user-images.githubusercontent.com/6177363/64474438-3a3d8580-d175-11e9-9a3f-6290402b4b31.png)

Output:

```
    public static class Contact
    {
        public const string EntityName = "contact";
        public const string EntityCollectionName = "contacts";
        public const string PrimaryKey = "address1_addressid";
        public const string PrimaryName = "fullname";
```

**Comment by rappen** [comment]
Wow, that looks quite bad! I'll try to repro.

**Comment by mikefactorial** [comment]
I found the same issue. Fix #37 @maerger put in seems to do the trick, but just a thought. Wouldn't it be more reliable to do this?
 
`        internal AttributeMetadataProxy PrimaryKey { get => Attributes?.FirstOrDefault(a => a.Metadata.LogicalName == Metadata?.PrimaryIdAttribute); }
`
So you're always pulling the attribute that the entity metadata says is the PrimaryKey could do the same for the PrimaryAttribute

`internal AttributeMetadataProxy PrimaryName { get => Attributes?.FirstOrDefault(a => a.Metadata.LogicalName == Metadata?.PrimaryNameAttribute); }
`

**Comment by maerger** [comment]
Sounds good to me - feel free to change...

**Comment by rappen** [comment]
It will be fixed in next release!
And yes @mikefactorial I have no idea why I didn't do like you suggest from the beginning... 🙄
