### ISSUE TITLE
File not found error when trying to use plugin

### ISSUE THREAD

**Issue by Szaamaan** [rappen/LCG-UDG#62]
![image](https://user-images.githubusercontent.com/20863608/83519160-ccdc3c80-a4db-11ea-9df7-56d1284f6bce.png)
As per title - trying to use the plugin results in an error...

**Comment by rappen** [comment]
It pains me to suggest this - but could you try restarting XrmToolBox and try starting the tool again...?
I have seen similar behavior right after installation of the tool.

**Comment by Szaamaan** [comment]
> It pains me to suggest this - but could you try restarting XrmToolBox and try starting the tool again...?
> I have seen similar behavior right after installation of the tool.

I found it works best when XrmToolbox is started as admin. Otherwise I'd keep getting that error for some reason.
