### ISSUE TITLE
DisplayName of optionset attributes show DisplayName of the optionset

### ISSUE THREAD

**Issue by rappen** [rappen/LCG-UDG#63]
It should show the displayname of the attribute, not the optionset.

---
- Deployment: Online
- DB Version: 9.1.0.19857
- Connection Controls Version: 1.2020.5.33
- XrmToolBox Version: 1.2020.6.40
- Tool Version: 1.2020.2.1

**Comment by daryllabar** [comment]
Agreed...

**Comment by rappen** [comment]
It seems that was fixed... ways back... weird....
