### ISSUE TITLE
Error loading Latebound Constants Generator

### ISSUE THREAD

**Issue by daryllabar** [rappen/LCG-UDG#64]
![image](https://user-images.githubusercontent.com/9728423/94605718-7f909180-0267-11eb-8f55-f591039ed4ab.png)

**Comment by daryllabar** [comment]
Restarted the toolbox, and it worked.

**Comment by rappen** [comment]
Have you hit your head?
Are you okay?
Covid struck Indiana?
I'm in shock over here.
