### ISSUE TITLE
NonPrintable Characters for OptionSets

### ISSUE THREAD

**Issue by daryllabar** [rappen/LCG-UDG#70]
In order to an option set that starts with numbers on a view I prefixed them with some funky unicode character...  This broke the LBC build due to ?'s :

![image](https://user-images.githubusercontent.com/9728423/103940348-2acca480-50fb-11eb-86eb-3f1d21867d52.png)

**Comment by rappen** [comment]
Aouch.
Example of your funky names?

**Comment by daryllabar** [comment]
The value I used is the blank space from here: https://emptycharacter.com/
