### ISSUE TITLE
Add support for PlantUML themes (colors)

### ISSUE THREAD

**Issue by Warp999** [rappen/LCG-UDG#75]
PlantUML provides many out of the box color themes (using the !theme directive). The XrmToolBox plugin hard codes colors. If possible, colors from the chosen theme should be respected.

Applying a theme to the generated PlantUML file today often results in unreadable diagrams.

**Comment by rappen** [comment]
[sorry crazy long time before I responded 🙄]

Good idea!
Can you show me some examples, using a theme for these models?
Do you have a link for "normal" themes?

**Comment by rappen** [comment]
For next release it is possible to select Theme, either from the official themes, or to include any puml-file online.

Selecting one theme available is used:
```
!theme sketchy
```
![image](https://github.com/user-attachments/assets/21cbb481-066c-4859-9fa2-7d20efbf7d1d)


Entering an URL include the theme:
```
!include https://raw.githubusercontent.com/bschwarz/puml-themes/refs/heads/master/themes/materia-outline/puml-theme-materia-outline.puml
```
![image](https://github.com/user-attachments/assets/ae270176-9ac3-4b37-ba86-809e6484bbf6)
