### ISSUE TITLE
Let the user specify which entities are 'really' custom

### ISSUE THREAD

**Issue by jellevervloessem** [rappen/LCG-UDG#88]
It would be very handy that not all msdyn_ entities are also marked as custom.
I have lots of entities related to the Marketing, DualWrite, FieldService, Project Operations solutions that are not custom created by me or my team.
That is why I would like to mark entities as 'custom' by the publisher or prefix. So I can give our own entities a different color.
Or let the user add an extra style (or multiple) for entities with a specific prefix.

---
- Deployment: Online
- DB Version: 9.2.23034.220
- Connection Controls Version: 1.2022.10.54
- XrmToolBox Version: 1.2023.2.64
- Tool Version: 1.2023.2.1

**Comment by rappen** [comment]
That's a great idea!
I will fix it in some way...

**Comment by jellevervloessem** [comment]
For now I have a python script that adds a custom style for our company <Cegeka> that replaces the <custom> tag where the prefix is something like cgk_  (or new_ in some exceptional cases 😉).

In my case this is sufficient. But maybe the user wants to mark the prefixes which are custom? Or even more extreme: apply mulitple styles in function of some functional blocks (customer management, sales, DualWrite, marketing,...) -> now I'm more brainstorming 😄

**Comment by rappen** [comment]
🤯

**Comment by rappen** [comment]
Added this is a common setting, can be manually updated to include more prefix to exclude.
Do we need more prefix now?

```
  <MicrosoftPrefixes>
    <string>msdyn_</string>
    <string>msdynce_</string>
    <string>msdyncrm_</string>
    <string>msdynmkt_</string>
    <string>msfp_</string>
    <string>mspcat_</string>
    <string>mspp_</string>
    <string>sales_</string>
    <string>adx_</string>
    <string>bot_</string>
    <string>botcomponent_</string>
  </MicrosoftPrefixes>
```
